### ISSUE TITLE
Consider testing polydet.github.io

### ISSUE THREAD

**Issue by Hugal31** [corkami/mitra#1]
Disclaimer: shameless advertising for a tool I developed.

In addition to `file` as a detection tool, you can try [polydet](https://polydet.github.io), a tool I developed with a friend when doing research about polyglots. It's empiric and only knows about [a few selected file formats](https://github.com/Polydet/polydet/tree/master/polydet/plugins), but can detect "suspicious byte chunks" in these formats. It shows better results than `file` (which it can use as a fallback) and TrID.

**Comment by angea** [comment]
TIL - thanks, I'll give it a try!
