### ISSUE TITLE
Directory 'static/' doesn't exist

### ISSUE THREAD

**Issue by ahsansiddz1** [corkami/mitra#14]
![image](https://user-images.githubusercontent.com/79744131/178890292-f9767e4c-b450-4e71-94a7-37c0818b6cc1.png)![image](https://user-images.githubusercontent.com/79744131/178890051-d8ca4c3e-967d-42d9-bc0a-f79297d11cf8.png)

**Comment by ahsansiddz1** [comment]
This method solved the error: 
* uninstall the existing fitz module/package
pip uninstall fitz
*Install pymupdf module
pip install pymupdf

but, 
it doesn't creates any new file
![image](https://user-images.githubusercontent.com/79744131/178891333-7476dd22-b108-4a38-bd7f-4469ab94a9cd.png)

**Comment by ahsansiddz1** [comment]
It worked on PNG/PDF <3
Maybe JPF/PDF isn't supported
![image](https://user-images.githubusercontent.com/79744131/178892093-80f10797-7783-4cbd-a2ff-367be1adb8aa.png)

**Comment by angea** [comment]
Use `--verbose` to know why each strategy failed.

**Comment by ahsansiddz1** [comment]
It would be helpful  if you describe all of the conversions that are supported by this program

**Comment by angea** [comment]
Yes, it's helpful: https://github.com/corkami/mitra#status
