### ISSUE TITLE
Unable to unzip files

### ISSUE THREAD

**Issue by A-Y-U-S-H-Y-A** [corkami/mitra#16]
PNG+ZIP
JPG+ZIP
JPG+7z

All generate an error while unzipping

`
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
`

**Comment by angea** [comment]
Try with a smaller Zip - in any case, Zip parsers behave differently.

**Comment by A-Y-U-S-H-Y-A** [comment]
> Try with a smaller Zip - in any case, Zip parsers behave differently.

The zip file only contains a single text file. Idts it can get any smaller

**Comment by angea** [comment]
Hard to tell without any details.
