### ISSUE TITLE
Zip and png/jpg files

### ISSUE THREAD

**Issue by aekramer** [corkami/mitra#6]
When running mitra using a ZIP and PNG or JPG (in that order) it will not generate any file. (It will print both file names and then their type, but it wont provide the Stack and Parasite messages)

When reversing the order, you get the 2 files and the full message, however the ZIP is not recognized as a valid archive.

For testing purposes, I did get it to work using a PDF and ZIP, I am assuming there is an issue with PNG/JPG? Which seems odd as it is one of the files from the example.

**Comment by angea** [comment]
- The behavior (no file with ZIP+PNG, stack and parasite with PNG+ZIP) is normal.
- the stack PNG-ZIP should work in all cases. Re-open if not.
- the parasite should work if the PNG is not too big, or with different unzipper software: in practice, the ZIP payload should be located 64 kb from the *end* of the file - and that's the only format that does that, and Mitra doesn't cover that special case - so if the PNG main data is bigger than that, the ZIP payload won't be found.

**Comment by aekramer** [comment]
> * The behavior (no file with ZIP+PNG, stack and parasite with PNG+ZIP) is normal.
> * the stack PNG-ZIP should work in all cases. Re-open if not.
> * the parasite should work if the PNG is not too big, or with different unzipper software: in practice, the ZIP payload should be located 64 kb from the _end_ of the file - and that's the only format that does that, and Mitra doesn't cover that special case - so if the PNG main data is bigger than that, the ZIP payload won't be found.

Could you provide a PNG that does work?

I have tried multiple by now, even used one with tinypng (that is 14.5kb in size now) and none seem to provide a valid zip file (using windows archive, 7zip and winrar)
