### ISSUE TITLE
Unzipping gives warning

### ISSUE THREAD

**Issue by Apro123** [corkami/mitra#7]
When doing a simple polyglot of a png and a zip file on a mac, it works perfectly.

When opening the png, it works fine. However, when trying to unzip it, it becomes a problem on a Mac OSX Catalina.

I am unable to unzip it simply by clicking it. 

<img width="390" alt="Screen Shot 2020-12-29 at 6 27 10 PM" src="https://user-images.githubusercontent.com/22110394/103326044-78625680-4a03-11eb-8de8-81da6ac831d1.png">

If I manually unzip it using the command line, I get this:

<img width="658" alt="Screen Shot 2020-12-29 at 6 28 05 PM" src="https://user-images.githubusercontent.com/22110394/103326074-98921580-4a03-11eb-8ccf-a6ee1ea8703c.png">

I know that this is the expected behavior of this wonderful program, but I wanted to get your thoughts on this and perhaps maybe there is a way to allow for no simple detection of polyglots.

**Comment by angea** [comment]
Some programs prefer if the internal offsets are adjusted.
This is not supported yet.
