### ISSUE TITLE
No file created

### ISSUE THREAD

**Issue by nahiiko** [corkami/mitra#8]
Hi !

I cloned the repo, am using python 3.6 and have no particular issue while using the script BUT, I just get nothing outputted.
I'm trying to "merge" ball2 into ball so that I have ball.jpg that can also be ball2.png once encrypted (or the other way around doesn't matter, by the way, why can't we do polyglots of same type ? png/png jpg/jpg for ex.)
am I missing something ?

![image](https://user-images.githubusercontent.com/72504666/108914040-18ff7c00-762b-11eb-9c9d-5178e8495fa8.png)
![image](https://user-images.githubusercontent.com/72504666/108913997-0b49f680-762b-11eb-8087-4aa8318af15f.png)

**Comment by angea** [comment]
Try with `--verbose` ?

**Comment by nahiiko** [comment]
Thanks for the tip didn't know the cmd, here's the result:
![image](https://user-images.githubusercontent.com/72504666/109300649-13768180-7837-11eb-8593-4ea9e205e749.png)

Seems like file size is an issue ?

**Comment by angea** [comment]
File size could be fixed indeed, but the offset start can't be solved.
You can't make a PNG/JPG polyglot, they both start at offset zero with different magics.

**Comment by nahiiko** [comment]
Ahhh that's a bummer !
Thanks for the support though !
